apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: "2025-12-31T16:43:34Z"
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::522534289017:role/eksctl-robomart-dev-nodegroup-robo-NodeInstanceRole-ewd165NPVCDl
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - groups:
      - tarinee
      userarn: arn:aws:iam::522534289017:user/rahul
      username: rahul
    - groups:
      - cl-admin
      userarn: arn:aws:iam::522534289017:user/suresh
      username: suresh

